<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Shanti-Windows-Laptop" failures="4" tests="5" name="org.github.tests.ValidateAddUpdateDeleteRepo_Functionality" time="0.810" errors="0" timestamp="2024-03-31T20:50:18 PDT" skipped="0">
  <testcase classname="org.github.tests.ValidateAddUpdateDeleteRepo_Functionality" name="validateDeleteRepo_NonExistentRepo" time="0.381"/>
  <system-out/>
  <testcase classname="org.github.tests.ValidateAddUpdateDeleteRepo_Functionality" name="validateUpdateRepoFunctionality" time="0.088">
    <failure message="create new repo functionality is failing due to :: Invalid number of path parameters. Expected 0, was 2. Redundant path parameters are: owner=RenuDix, repo=Fakercom.github.javafaker.FunnyName@3b4ef59f." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: create new repo functionality is failing due to :: Invalid number of path parameters. Expected 0, was 2. Redundant path parameters are: owner=RenuDix, repo=Fakercom.github.javafaker.FunnyName@3b4ef59f.
at org.testng.Assert.fail(Assert.java:97)
at com.github.base.APIHelper.addData(APIHelper.java:120)
at org.github.tests.ValidateAddUpdateDeleteRepo_Functionality.validateCreateRepoFunctionality(ValidateAddUpdateDeleteRepo_Functionality.java:53)
at org.github.tests.ValidateAddUpdateDeleteRepo_Functionality.validateUpdateRepoFunctionality(ValidateAddUpdateDeleteRepo_Functionality.java:122)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateUpdateRepoFunctionality -->
  <system-out/>
  <testcase classname="org.github.tests.ValidateAddUpdateDeleteRepo_Functionality" name="validateCreateRepoFunctionality1" time="0.059">
    <failure message="create new repo functionality is failing due to :: Invalid number of path parameters. Expected 0, was 2. Redundant path parameters are: owner=RenuDix, repo=Fakercom.github.javafaker.FunnyName@3b4ef59f." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: create new repo functionality is failing due to :: Invalid number of path parameters. Expected 0, was 2. Redundant path parameters are: owner=RenuDix, repo=Fakercom.github.javafaker.FunnyName@3b4ef59f.
at org.testng.Assert.fail(Assert.java:97)
at com.github.base.APIHelper.addData(APIHelper.java:120)
at org.github.tests.ValidateAddUpdateDeleteRepo_Functionality.validateCreateRepoFunctionality(ValidateAddUpdateDeleteRepo_Functionality.java:53)
at org.github.tests.ValidateAddUpdateDeleteRepo_Functionality.validateCreateRepoFunctionality1(ValidateAddUpdateDeleteRepo_Functionality.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateCreateRepoFunctionality1 -->
  <system-out/>
  <testcase classname="org.github.tests.ValidateAddUpdateDeleteRepo_Functionality" name="validateCreateRepoFunc_ExistingRepoName" time="0.220">
    <failure message="create new repo functionality is failing due to :: Invalid number of path parameters. Expected 0, was 2. Redundant path parameters are: owner=RenuDix, repo=Fakercom.github.javafaker.FunnyName@3b4ef59f." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: create new repo functionality is failing due to :: Invalid number of path parameters. Expected 0, was 2. Redundant path parameters are: owner=RenuDix, repo=Fakercom.github.javafaker.FunnyName@3b4ef59f.
at org.testng.Assert.fail(Assert.java:97)
at com.github.base.APIHelper.addData(APIHelper.java:120)
at org.github.tests.ValidateAddUpdateDeleteRepo_Functionality.validateCreateRepoFunctionality(ValidateAddUpdateDeleteRepo_Functionality.java:53)
at org.github.tests.ValidateAddUpdateDeleteRepo_Functionality.validateCreateRepoFunc_ExistingRepoName(ValidateAddUpdateDeleteRepo_Functionality.java:88)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateCreateRepoFunc_ExistingRepoName -->
  <system-out/>
  <testcase classname="org.github.tests.ValidateAddUpdateDeleteRepo_Functionality" name="validateDeleteRepo" time="0.062">
    <failure message="create new repo functionality is failing due to :: Invalid number of path parameters. Expected 0, was 2. Redundant path parameters are: owner=RenuDix, repo=Fakercom.github.javafaker.FunnyName@3b4ef59f." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: create new repo functionality is failing due to :: Invalid number of path parameters. Expected 0, was 2. Redundant path parameters are: owner=RenuDix, repo=Fakercom.github.javafaker.FunnyName@3b4ef59f.
at org.testng.Assert.fail(Assert.java:97)
at com.github.base.APIHelper.addData(APIHelper.java:120)
at org.github.tests.ValidateAddUpdateDeleteRepo_Functionality.validateCreateRepoFunctionality(ValidateAddUpdateDeleteRepo_Functionality.java:53)
at org.github.tests.ValidateAddUpdateDeleteRepo_Functionality.validateDeleteRepo(ValidateAddUpdateDeleteRepo_Functionality.java:143)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateDeleteRepo -->
  <system-out/>
</testsuite> <!-- org.github.tests.ValidateAddUpdateDeleteRepo_Functionality -->
